spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #for load balancer
      routes:
        - id: account
          predicates:
            - Path=/api/account
            - Method=GET
          uri: lb://ms-account


server:
  port: 8020

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


