spring:
  application:
    name: ms-payment
  devtools:
    remote:
      restart:
        enabled: true

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
