spring:
  application:
    name: ms-payment
  devtools:
    remote:
      restart:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/ms_payment
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml


server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




client:
  ms-card:
    endpoint: http://localhost:8020/ms-card/


#for circuit breaker
management:
  health:
    circuit-breakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j.circuit-breaker:
    instances:
      external:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 30s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-size: 4
        sliding-window-type: COUNT_BASED
