spring:
  application:
    name: ms-account
  devtools:
    remote:
      restart:
        enabled: true

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  #for load balancer
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}